markdown: redcarpet
name: Authentication Guide [DRAFT]
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go

permalink: pretty
highlighter: rouge

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  url: index.html
  internal: true
- text: Use cases
  url: use-cases/
  internal: true
- text: Avoiding replay attacks
  url: avoiding-replay-attacks/
  internal: true
- text: HTTPS and SSL/TLS
  url: https/
  internal: true
- text: Oauth
  url: oauth/
  internal: true
  children:
  - text: oauth2_proxy
    url: oauth2_proxy/
    internal: true
- text: Hash-based Message Authentication Codes
  url: hmac/
  internal: true
  children:
  - text: HMAC web server middleware
    url: middleware/
    internal: true
  - text: HMAC proxy server
    url: hmacproxy/
    internal: true
- text: Auth delegation server
  url: authdelegate/
  internal: true

repos:
- name: Authentication Guide Repo
  description: Main repository
  url: https://github.com/18F/authentication

back_link:
  url: "https://pages.18f.gov/guides/"
  text: Read more 18F Guides

google_analytics_ua: UA-48605964-19

defaults:
  -
    scope:
      path: ""
    values:
      layout: "guides_style_18f_default"
